version: '3.3'

services:
  frontend:
    build: 
      context: ./vue
      args:
        VUE_APP_API_HOST: '/api'
    ports:
      - 80:8081

  backend:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8082

    # for local library
    volumes:
      - ./../src/pyPhraseSuggester:/app/pyPhraseSuggester:ro
    # ports:
    #   - 8082:8082